# Generated by Django 4.2.8 on 2023-12-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_vendor_id_alter_vendor_vendor_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
