# Generated by Django 4.2.8 on 2023-12-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_purchaseorder_historicalperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
    ]
