# Generated by Django 4.2.8 on 2023-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_historicalperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.TextField(),
        ),
    ]
